.PHONY: clean All

All:
	@echo "----------Building project:[ DataStructures - Debug ]----------"
	@cd "DataStructures" && "$(MAKE)" -f  "DataStructures.mk"
clean:
	@echo "----------Cleaning project:[ DataStructures - Debug ]----------"
	@cd "DataStructures" && "$(MAKE)" -f  "DataStructures.mk" clean
