.PHONY: clean All

All:
	@echo "----------Building project:[ Assign_8 - Debug ]----------"
	@cd "Assign_8" && "$(MAKE)" -f  "Assign_8.mk"
clean:
	@echo "----------Cleaning project:[ Assign_8 - Debug ]----------"
	@cd "Assign_8" && "$(MAKE)" -f  "Assign_8.mk" clean
