.PHONY: clean All

All:
	@echo "----------Building project:[ Assign_6 - Debug ]----------"
	@cd "Assign_6" && "$(MAKE)" -f  "Assign_6.mk"
clean:
	@echo "----------Cleaning project:[ Assign_6 - Debug ]----------"
	@cd "Assign_6" && "$(MAKE)" -f  "Assign_6.mk" clean
